Pycord-Development/pycord

- discord/bot.py
> Changed AppMixin, BotBase, SlashCmds, etc

- README.ja.rst
- README.rst
The README had the wrong link in the git clone command.
> Fix READMEs

- discord/__main__.py
Changes discord.py mention to pycord, there is also [this](https://github.com/yo56789/pycord/blob/master/discord/http.py#L183) which needs to be changed but idk if it would break something
> fix discord.py to pycord

- discord/errors.py
- discord/utils.py
Reverts Pycord-Development/pycord#42
> Revert "Implements a new `get_or_fetch` feature"

- examples/converters.py
Minor PR to fix 2 incorrect doc links. Nothing to it 🤷
> MINOR discordpy >> pycord doc links update

- discord/app/context.py
- discord/interactions.py
Added Allowed Mentions to interaction responses
Added author to context for consistency with dpy
> Add allowed_mentions to respond and author to context

- discord/app/context.py
> Typehint and document discord/app/context.py

- discord/app/context.py
> Fix ictx.message type

- discord/client.py
This makes the invalid token type error more understandable.
> Make invalid token type raise TypeError

- discord/errors.py
Replaced `loaded` with `found` to make the error message of `ExtensionNotFound` be more useful.
> Improve message for `ExtensionNotFound`

- examples/app_commands/slash_options.py
This PR adds a missing bot.run() line.
> Add missing Bot.run() line

- discord/__init__.py
- discord/guild.py
- discord/http.py
- discord/welcome_screen.py
- docs/api.rst
Implemented support for guild welcome screen.
> Add support for Welcome screen

- about.md
It does not fix any issues, it just makes About.MD a bit better
> Making about.md a little bit better

- discord/app/commands.py
Apparently last time I PR'd to the wrong branch :cry:. Anywho, this PR is the same as the other one.
> Add __call__ to ApplicationCommand

- discord/ext/commands/bot.py
Extension errors were moved to discord from commands. This PR replaces all the errors with the new ones.
> Replace extension errors with new ones.

- discord/ext/commands/core.py
Implements #223.
Couldn't test since the restructure branch isn't usable.
> Implement Command.cooldown

- .github/workflows/codespell.yml
- discord/bot.py
- discord/ext/commands/cooldowns.py
- discord/ext/commands/errors.py
- discord/object.py
- discord/state.py
- discord/ui/item.py
- discord/utils.py
- docs/intro.rst
- docs/locale/ja/LC_MESSAGES/api.po
- docs/locale/ja/LC_MESSAGES/ext/commands/api.po
- docs/locale/ja/LC_MESSAGES/intro.po
- examples/app_commands/slash_basic.py
- examples/app_commands/slash_options.py
[`codespell --ignore-words-list="groupt,nd,ot"`](https://pypi.org/project/codespell)
Test results: https://github.com/cclauss/pycord/actions
> Fix typos discovered by codespell

- discord/ui/view.py
This aims to make views easier to create and use.
> Add *items to View

- discord/http.py
Set the user-agent for this project per https://discord.com/developers/docs/reference#user-agent
> Set pycord user-agent

- discord/abc.py
Reverts Pycord-Development/pycord#243
> Revert "Revert "Add `can_send` method to Messageable""

- discord/guild.py
- discord/http.py
- discord/types/guild.py
> Add `guild.premium_progress_bar_enabled`

- examples/app_commands/slash_perms.py
Updates the slash_perms.py example to use permissions.py
> Update slash_perms.py example

- discord/utils.py
> Changes Docs to look better.

- discord/guild.py
> Add guild feature

- README.ja.rst
> Update Japanese Readme

- README.ja.rst
Fixed guild id for member online count and added download badge
> Quick fix of japanese readme

- .github/workflows/bandit.yml
[`bandit --recursive  --skip B101,B104,B105,B110,B307,B311,B404,B603,B607 .`](https://pypi.org/project/bandit/)
Results: https://github.com/cclauss/pycord/actions
> GitHub Action to run a security scan using bandit

- discord/http.py
We're using v9 for the websocket gateway but v8 for http.
Updated http endpoint to v9.
> Change http gateway version

- discord/flags.py
- discord/permissions.py
Added the permission `MANAGE_MEMBERS` with a value of `1<<40`.
Removed non-public flags from `PublicUserFlags`
> New permission 1<<40

- discord/utils.py
Fixes merge errors in utils.basic_autocomplete
> Fix merge errors in utils.basic_autocomplete

- discord/guild.py
- discord/http.py
- discord/welcome_screen.py
Fixes some wrong imports and typings
> Fix WelcomeScreen typings

- about.md
Update old discord link in the about.md file.
> Update Discord Link in about.md

- README.rst
> better discord shield

- discord/asset.py
- discord/bot.py
- discord/commands/_types.py
- discord/commands/commands.py
- discord/commands/context.py
- discord/commands/errors.py
- discord/commands/permissions.py
- discord/ext/commands/bot.py
- discord/ext/commands/converter.py
- discord/ext/commands/help.py
- discord/ext/commands/view.py
- discord/flags.py
- discord/http.py
- discord/integrations.py
- discord/mentions.py
- discord/partial_emoji.py
- discord/types/interactions.py
- discord/utils.py
- discord/webhook/async_.py
- discord/webhook/sync.py
- discord/welcome_screen.py
This is a work in progress pr for fully type hint discord commands.
Due to a larger restructure, I had to create a new pr. 
Original Pr: #133
> Type hinting for discord.commands

- discord/member.py
- discord/types/member.py
> baseholder implementation for timeouts

- examples/app_commands/slash_groups.py
Fixes examples/slash_groups.py by updating it to use `bot.create_group()`
Closes #574
> fix for slash groups example

- examples/interactionsBot/bot.py
- examples/interactionsBot/cog_group/__init__.py
- examples/interactionsBot/cogs/button_cog.py
- examples/interactionsBot/cogs/dropdown_cog.py
- examples/interactionsBot/cogs/slashGroup_cog.py
- examples/interactionsBot/cogs/slashOption_cog.py
- examples/interactionsBot/cogs/slash_cog.py
#248 
interactions for cogs with better examples
> Add More examples

- .gitignore
- docs/application_commands.rst
> Document slash command groups

- discord/client.py
Adds a new `Client.get_or_fetch_user` method that uses `utils.get_or_fetch`.
> New `get_or_fetch_user` method

- .github/CODEOWNERS
havent fully finished it but codeowners!
They will be automatically asked for review and either @CodeWithSwastik or @BobDotCom can
require reviews from codeowners in branch protection if they want to
> Making A CODEOWNERS

- discord/asset.py
This PR adds support for animated guild banners.
> Add support for animated guild banners

- discord/interactions.py
- discord/message.py
- discord/utils.py
> Add delay and delete_after Parameters on Interaction functions

- discord/member.py
Fixes an error being produced when a user has a guild avatar, due to improper imports. Thanks to @MhmCats for helping to find the issue.
> Fix guild avatars not working

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
Makes recommendations to use certain style guides
> Commit Styling

- discord/ext/pages/pagination.py
This commit adds a function to allow you to update the amount of pages
of the `Paginator` instance.
This might be usefull if you change amount of pages depending on a
dropdown (SelectionOption)
> Add functionality to update `Paginator`

- discord/commands/commands.py
- discord/commands/context.py
Followup of #443, closes #442.
> Implement ApplicationContext.invoke

- discord/bot.py
Reverts Pycord-Development/pycord#647
> Revert "Ability to reload application command callbacks"

- discord/commands/commands.py
- discord/commands/permissions.py
- examples/app_commands/slash_cog_groups.py
- examples/app_commands/slash_perms.py
Un-stale version of #543 by @thereaper62. Closes #416.
> Rename Permission to CommandPermission

- discord/file.py
- discord/http.py
- discord/interactions.py
- discord/message.py
- discord/webhook/async_.py
Adds the `description` attribute to `Attachment` and `File`
@zeffo helped with implementing file sending.
Resolves #483
> Add description to Attachments and Files

- discord/threads.py
- discord/types/threads.py
> Remove Thread.archiver_id

- discord/bot.py
Reverts Pycord-Development/pycord#670
> Add ability to reload application command callbacks back

- docs/api.rst
Document RawScheduledEventSubscription
> Document Missing Raw Payload

- discord/raw_models.py
> Fix documentation inconsistency

- discord/commands/commands.py
Closes #716.
- [x If code changes were made then they have been tested.
> Fix Max Concurrency On Application Commands

- discord/commands/commands.py
> Fix #716 and #718

- discord/bot.py
- discord/commands/commands.py
May need further testing just in case I missed something.
~~also can y'all check the type annotations I have a feeling there's something wrong there~~
> Add Walk (application) Commands on `SlashCommandGroup` and `discord.Bot`

- discord/bot.py
> Use data.get for optional guild_id parameter

- discord/scheduled_events.py
- docs/api.rst
> Fix ScheduledEventLocation documentation

- discord/audit_logs.py
- discord/guild.py
- discord/scheduled_events.py
> Fix attribute error for ScheduledEventLocation

- discord/ext/pages/pagination.py
Fixes an issue with documentation and a missing backtick causing weird behaviour
> Fixed missing backtick causing problems

- .github/CONTRIBUTING.md
Fix discord.py StackOverflow reference in CONTRIBUTING.md
> Update StackOverflow tag in CONTRIBUTING.md

- docs/intro.rst
Add pip install from git to intro docs to help newcomers.
> Add git command and warning to introduction

- docs/intro.rst
> Should probably include windows users

- docs/intro.rst
> fix: incorrect year

- discord/cog.py
- discord/commands/core.py
- discord/ext/commands/cog.py
- discord/ext/pages/pagination.py
- discord/flags.py
- discord/http.py
- discord/integrations.py
- discord/interactions.py
- discord/message.py
- discord/role.py
- discord/state.py
- discord/template.py
- discord/widget.py
- Removes unused imports
- Adds missing imports
- Uses `type: ignore` when necessary
- Changes an incorrect `Union`
> Typing and importing fixes

- setup.py
> chore: bump sphinx to `4.4.0`

- discord/state.py
Fixes scheduled event gateway events not working, brought up in the [discord server](https://canary.discord.com/channels/881207955029110855/881735314987708456/932785670257258576).
> Fix ScheduledEvent (gateway) events not working

- discord/asset.py
- discord/http.py
- discord/scheduled_events.py
- discord/types/scheduled_events.py
Add support for scheduled event cover images
idk if this should count as a feature
> Add cover images

- discord/interactions.py
- discord/message.py
- discord/types/interactions.py
Implement `MessageInteraction` class. ([link to the Discord docs](https://discord.com/developers/docs/interactions/receiving-and-responding#message-interaction-object-message-interaction-structure))
This can be used like `message.interaction`.
Fixes #792.
> Implement MessageInteraction class

- discord/http.py
- discord/iterators.py
- discord/scheduled_events.py
- setup.py
Followup to #781
Fixes #771, #772, #773, #780
> Fix behaviour of ScheduledEvent subs iterator

- discord/sinks/core.py
- examples/audio_recording.py
> feat: add get audio functions

- discord/commands/options.py
> Add license to commands/options.py

- docs/api.rst
Added documentation for the `MessageInteraction` class.
> Add docs for `MessageInteraction` class

- discord/__init__.py
- setup.py
> Bump version to 2.0.0 beta

- setup.py
Fixes error when downloading on github, this error shouldn't persist on pypi.
> fix: add sinks to packages

- discord/sinks/core.py
> fix: imports

- discord/bot.py
Solution for `AttributeError: NoneType object has no attribute 'id'` for `Bot.sync_commands`
> Fix AttributeError

- discord/voice_client.py
Fix small typo for doc in `voice_client.py`
> Fix typo in `voice_client.py`

- discord/bot.py
This fixes the issue mentioned here: https://ptb.discord.com/channels/881207955029110855/881735314987708456/939585751904034926
> Fix getting desynced commands

- discord/bot.py
> Fix doc typo in `bot.py`

- discord/bot.py
> Raise fatal errors on permissions failure

- docs/api.rst
This adds `Modal` and `InputText` to the documentation under the Bot UI Kit heading.
> Add modals to docs

- discord/interactions.py
Adds a custom_id attribute to Interaction.
> Add custom_id attribute to Interaction

- discord/interactions.py
Allows modal submit interactions to be deferred.
> Allow deferring of modal submits

- discord/__init__.py
Fixes import inconsistency in \_\_init\_\_.py
> Replace scheduled event imports with wildcard

- discord/interactions.py
- discord/ui/input_text.py
- discord/ui/modal.py
This adds new and updated docstrings to `Modal`, `InputText`, and `InteractionResponse.send_modal()`.
> Add and update docstrings for `Modal` and `InputText` objects and related methods

- docs/api.rst
This adds doc tables for the `CommandPermission` class and its decorator functions.
> Add `CommandPermission` docs

- examples/timeout.py
In one example a small mistake was made, I have fixed it.
> Mistake in an example 

- discord/webhook/async_.py
- docs/api.rst
- docs/ext/commands/commands.rst
Fixes some issues with the format of the docs.
> Fix format issues in documentation

- discord/bot.py
> Add `Bot.invoke_application_command`

- examples/views/dropdown.py
in the class Dropdown(discord.ui.Select) it is now possible to use self.bot
Some people wanted an example that you can work with self.bot in the callbacks.
What do you think about it?
> Small change to the DropDown example

- examples/new_member.py
Fixes typo in `new_member` example
> Fix typo in `new_member` example

- README.rst
> Slight change in README

- discord/commands/context.py
- discord/interactions.py
These typehints seem to be incorrect.
> Fix typehints for `send_modal` methods

- discord/client.py
- discord/flags.py
- docs/faq.rst
> Add `Client.get_message`

- discord/cog.py
This PR adds cog support for Bridge Commands.
> chore: add cog support for Bridge Commands

- README.rst
Updated README code examples to reflect the change to privileged intent for message content.
> Update README code example

- discord/guild.py
- discord/http.py
- discord/iterators.py
> Ban pagination

- discord/__init__.py
> Fix mypy error when type checking pycord with `namespace_packages` flag

- discord/commands/core.py
> Check if the target is a system or bot message

- discord/ext/pages/pagination.py
Adds delete_after for paginator.send
> Adding delete_after for paginator.send

- discord/abc.py
- discord/channel.py
> Add `jump_url` property to channels

- discord/threads.py
> Add `jump_url` Property to Threads

- discord/state.py
> Remove voice client when bot disconnects

- discord/guild.py
> Add Guild.jump_url

- .github/workflows/bandit.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/codespell.yml
- .github/workflows/mypy.yml
- .github/workflows/pylint.yml
- .github/workflows/python-app.yml
- .gitignore
- .pylintrc
- examples/app_commands/slash_autocomplete.py
- examples/app_commands/slash_options.py
- examples/audio_recording.py
- examples/timeout.py
- mypy.ini
- pytest.ini
- requirements-dev.txt
- tests/helpers.py
- tests/test_utils.py
> Improve CI

- docs/api.rst
Documents new audit log attributes
> Perms v2 Audit Log Documentation

- discord/interactions.py
Please correct me if I'm wrong, but this should be better, but this is slightly more readable in my opinion, and even though it *might* be faster with Python's EAFP logic, I think maintainability and readability is probably more important than this micro efficiency.
> Minor Refactor

- discord/audit_logs.py
Adds cover support to audit logs
> Support event covers for audit logs

- .github/ISSUE_TEMPLATE/feature_request.yml
> Add ext.bridge to issue selection

- discord/guild.py
Updates premium guild limits to reflect the newly set sticker limits.
> Update to new sticker limit

- discord/audit_logs.py
- discord/ext/commands/flags.py
> Improve Code

- discord/user.py
> Add a `jump_url` property to users

- discord/ext/commands/converter.py
- discord/partial_emoji.py
- discord/utils.py
- discord/webhook/async_.py
- discord/webhook/sync.py
Simple modification of regular expressions.
change regular expression format.
like this...
`[0-9]` -> `\d`
`[A-Za-z0-9\_]` -> `\w`
[You can check it here.](https://regex101.com/r/KRV4tW/1)
(If you are doing this intentionally, you may close it.)
> Regular expression changes

- discord/audit_logs.py
- discord/enums.py
This PR fixes a small return signature issue and updates an incorrect number in `enums.py`.
> Small code fixes

- examples/audio_recording.py
Its probably better to be this way actually, i tested - works fine.
Remade if else spam part using dict, this will probably work faster and just looks better.
> Remade if else spam part to dict

- discord/commands/context.py
Simply just added missing documentation for ApplicationContext.
> Update ApplicationContext Documentation

- docs/whats_new.rst
> Bump 2.0.0 Changelog.

- discord/cog.py
This PR is from this conversation:
https://discord.com/channels/881207955029110855/881735314987708456/1003029839609073736
> Fix load_extensions parameters not being passed through

- examples/new_member.py
Let's be real, no one, who needs those examples, will use subclassing style. Most of other examples are using this ^ style to show stuff.
> Improved examples to be easier.

- discord/ui/view.py
Currently the message is just plain-text, this PR fixes it so it points to the message object.
> Fixed documentation error link

- .github/ISSUE_TEMPLATE/vulnerability_report.yml
- .github/workflows/codespell.yml
Probably fixed the codespell thing, added few words to ignore list and fixed one typo. (I hope it works)
*It triggered to `ro` locale, what did Romanian do to codespell...*
> Fix to the codespell test error.

- discord/commands/permissions.py
It makes the example look correct on the Docs. This is what is currently looks like: https://docs.pycord.dev/en/master/api.html#discord.commands.guild_only
> Fix Example Typo/Syntax Error

- discord/bot.py
- discord/commands/context.py
- discord/ext/commands/bot.py
- discord/ext/commands/context.py
- discord/ext/commands/converter.py
- discord/iterators.py
- discord/webhook/sync.py
> Remove unused imports and variables

- discord/state.py
This pull request reverts #1273 as it caused a separate issue.
Fixes #1567
> Fix VOICE_SERVER_UPDATE error

- discord/utils.py
This pull request improves the `utils.deprecated` decorator with new parameters and adds a new `utils.warn_deprecated` function as a non-decorator alternative. Test code and results below.
<details>
<summary>Test Code</summary>
```py
from discord.utils import deprecated
from itertools import combinations, chain
entries = ["instead", "since", "removed", "reference", "use_qualname"]  # Possible keys
e_iter = chain([tuple()], chain.from_iterable(combinations(entries, i + 1) for i in range(len(entries))))
for combo in e_iter:
class Test:
@staticmethod
@deprecated(
"new_func" if "instead" in combo else None,
"2.0" if "since" in combo else None,
"3.0" if "removed" in combo else None,
"#1234" if "reference" in combo else None,
use_qualname="use_qualname" in combo,
)
def old_func():
... …
```
> Upgrade utils.deprecated & add utils.warn_deprecated

- discord/guild.py
> chore: better typehint

- CHANGELOG.md
This PR adds a missing parenthesis to `CHANGELOG.md`.
> Fix changelog for #1609

- README.rst
Commas are not used to separate independent clauses.
It fixes a grammar mistake.
> fix: README.rst grammar

- discord/utils.py
> Minor get_or_fetch docs fix

- discord/_version.py
> Correct version_info number type

- docs/api/enums.rst
> chore(docs): attachment option type no longer in beta

- examples/views/channel_select.py
Adds an example for the new channel selects
> docs: Add channel select example

- examples/views/role_select.py
Adds an example of the new role selects
> docs: Add role select example

- discord/guild.py
1. The current list is missing newer features.
2. Let another source update these changes instead.
> docs: add a link to guild features

- CHANGELOG.md
- discord/embeds.py
Reverts Pycord-Development/pycord#2061
> chore!: "fix: add defaults to __init__s on embed classes"

- discord/embeds.py
> fix: embeds having weird state

- CHANGELOG.md
> docs(changelog): log username change

- discord/user.py
> fix: default avatar % 6 if migrated

- discord/commands/options.py
Fixes a broken link in the [`discord.option`](https://docs.pycord.dev/en/master/api/application_commands.html#discord.commands.option) decorator.
> docs: fix broken link

- discord/colour.py
The purpose of this is that the class in embed_background it says color even tho everywhere else it says colour
> docs: Change color to colour

- CHANGELOG.md
> docs: Update CHANGELOG.md with merged pull request #2164

- CHANGELOG.md
> docs: fix changelog mistakes

- .github/workflows/check.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- pyproject.toml
> feat: support python 3.12

- discord/ui/view.py
Use interaction routes to disable items if the view is in an ephemeral message. Fixes #2279 
> fix: handle ephemeral messages in `disable_on_timeout`

- CHANGELOG.md
Updates word choice and format of recent changelog entries.
This shall be merged right before the next release.
> chore: clean up changelog

- CHANGELOG.md
- discord/interactions.py
> fix: add `entitlements` to slots of `Interaction`

- discord/guild.py
> docs: remove false optional

- CHANGELOG.md
- discord/guild.py
- discord/http.py
> chore: remove `vanity_code` from `Guild.edit`

- discord/interactions.py
Missed this in my PR earlier I guess?
> docs: add docs for Interaction.entitlements

- discord/ui/input_text.py
> docs: minor `InputText` formatting issues

- docs/api/enums.rst
> docs: fix hyphen-related grammar

- CHANGELOG.md
Use past tense instead of present tense.
> docs: update changelog to be consistent

- discord/message.py
This PR adds a Notfound error in Message.edit.
> docs: Add missing error for Message.edit

- discord/client.py
Fixes https://github.com/Pycord-Development/pycord/issues/2399. Takes inspiration from https://github.com/Rapptz/discord.py/pull/1967.
> fix: prevent unclosed client session / unclosed connector

- discord/ui/view.py
> docs: :memo: Add timeout time to `View` docstring

- CHANGELOG.md
> docs: changelog grammar edits

- CHANGELOG.md
- discord/abc.py
> fix: :bug: handle None case for `default_reaction_emoji` in ForumChannel edit payload

- CHANGELOG.md
> docs: :memo: Fix malformed CHANGELOG.md hyperlinks

- CHANGELOG.md
- discord/audit_logs.py
> fix: :bug: Fix `AttributeError` when accessing `AuditLogEntry.changes` more than once
